#!/bin/bash

echo "🧪 Example curl command for /api/responses/evaluate endpoint:"
echo ""

echo "curl -X POST http://localhost:3000/api/responses/evaluate \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"sessionId\": \"1\","
echo "    \"questionId\": \"1\","
echo "    \"questionText\": \"Tell me about a time when you had to debug a complex JavaScript issue. How did you approach it?\","
echo "    \"textResponse\": \"I encountered a memory leak in a React application. I used Chrome DevTools to profile the memory usage and identified that event listeners were not being properly cleaned up. I implemented proper cleanup in useEffect hooks and the issue was resolved.\""
echo "  }'"

echo ""
echo "📝 Expected Response Format:"
echo "{"
echo "  \"success\": true,"
echo "  \"response\": { ... },"
echo "  \"evaluation\": {"
echo "    \"score\": 85,"
echo "    \"feedback\": \"Detailed feedback about the response...\","
echo "    \"strengths\": [\"Good technical detail\", \"Clear explanation\"],"
echo "    \"improvements\": [\"Could provide more context\", \"Consider mentioning specific tools\"],"
echo "    \"timeline_analysis\": {"
echo "      \"clarity\": 8,"
echo "      \"confidence\": 7,"
echo "      \"technical_depth\": 9,"
echo "      \"communication\": 8,"
echo "      \"structure\": 7,"
echo "      \"engagement\": 8,"
echo "      \"completeness\": 9"
echo "    }"
echo "  }"
echo "}"

echo ""
echo "⚠️  Note: Currently there's a database foreign key constraint issue"
echo "   that prevents the response from being stored, but the evaluation"
echo "   logic itself works correctly." 